<!DOCTYPE html>
<html>

<head>
    <title>Guest List - {{ $event->title }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #1e293b;
            line-height: 1.5;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
        }

        .header h1 {
            text-transform: uppercase;
            letter-spacing: -0.025em;
            margin: 0;
            font-size: 24px;
        }

        .header p {
            color: #64748b;
            font-size: 14px;
            margin: 5px 0 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background-color: #f8fafc;
            text-align: left;
            text-transform: uppercase;
            font-size: 10px;
            letter-spacing: 0.05em;
            padding: 12px;
            border-bottom: 1px solid #e2e8f0;
        }

        td {
            padding: 12px;
            border-bottom: 1px solid #f1f5f9;
            font-size: 12px;
        }

        .status-badge {
            font-size: 10px;
            padding: 2px 8px;
            border-radius: 9999px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .status-attending {
            background-color: #dcfce7;
            color: #166534;
        }

        .status-maybe {
            background-color: #fef9c3;
            color: #854d0e;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $event->title }}</h1>
        <p>Guest List | Generated on {{ now()->format('M d, Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @foreach($guests as $rsvp)
                <tr>
                    <td><strong>{{ $rsvp->user->name }}</strong></td>
                    <td>{{ $rsvp->user->email }}</td>
                    <td>
                        <span
                            class="status-badge {{ $rsvp->status === 'attending' ? 'status-attending' : 'status-maybe' }}">
                            {{ $rsvp->status }}
                        </span>
                    </td>
                    <td>{{ $rsvp->created_at->format('M d, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Pamoja Africa Event Planner
    </div>
</body>

</html>