<!DOCTYPE html>
<html>

<head>
    <title>Tasks Checklist - {{ $event->title }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #1e293b;
            line-height: 1.5;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
        }

        .header h1 {
            text-transform: uppercase;
            letter-spacing: -0.025em;
            margin: 0;
            font-size: 24px;
        }

        .header p {
            color: #64748b;
            font-size: 14px;
            margin: 5px 0 0;
        }

        .task-item {
            margin-bottom: 20px;
            padding: 15px;
            border: 1px solid #e2e8f0;
            border-radius: 12px;
        }

        .task-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 8px;
        }

        .task-title {
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
        }

        .task-status {
            font-size: 10px;
            font-weight: black;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            padding: 2px 8px;
            border-radius: 9999px;
        }

        .status-completed {
            background-color: #dcfce7;
            color: #166534;
        }

        .status-pending {
            background-color: #f1f5f9;
            color: #475569;
        }

        .task-details {
            font-size: 12px;
            color: #64748b;
            margin-top: 5px;
        }

        .task-description {
            font-size: 12px;
            color: #334155;
            margin-top: 10px;
            background: #f8fafc;
            padding: 10px;
            border-radius: 8px;
        }

        .meta-grid {
            margin-top: 10px;
            font-size: 11px;
            display: table;
            width: 100%;
        }

        .meta-item {
            display: table-cell;
            width: 33%;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $event->title }}</h1>
        <p>Tasks Checklist | Generated on {{ now()->format('M d, Y H:i') }}</p>
    </div>

    @foreach($tasks as $task)
        <div class="task-item">
            <div style="float: right;">
                <span class="task-status {{ $task->completed ? 'status-completed' : 'status-pending' }}">
                    {{ $task->completed ? 'Completed' : 'Pending' }}
                </span>
            </div>
            <div class="task-title">{{ $task->title }}</div>

            <div class="meta-grid">
                <div class="meta-item">
                    <strong>Assigned To:</strong> {{ $task->assignee ? $task->assignee->name : 'Unassigned' }}
                </div>
                <div class="meta-item">
                    <strong>Due Date:</strong> {{ $task->due_date ? $task->due_date->format('M d, Y') : 'N/A' }}
                </div>
            </div>

            @if($task->description)
                <div class="task-description">
                    <strong>Description:</strong><br>
                    {{ $task->description }}
                </div>
            @endif

            @if($task->completion_comment)
                <div class="task-description" style="border-left: 3px solid #10b981; background: #ecfdf5;">
                    <strong>Completion Note:</strong><br>
                    {{ $task->completion_comment }}
                </div>
            @endif
        </div>
    @endforeach

    <div class="footer">
        Generated by Pamoja Africa Event Planner
    </div>
</body>

</html>